openapi: 3.0.0
components:
  schemas:
    NewOrder:
      type: object
      required:
        - title
        - dinner_id
        - client_name
        - client_phone
        - price
        - calories
        - ingredients
      properties:
        title:
          type: string
          description: Order's name.
          example: "Hot-Dog"
        dinner_id:
          type: string
          description: Dinner's id.
          example: "611273f32335860890b58056"
        client_name:
          type: string
          description: Name of client making order.
          example: "John Doe"
        client_phone:
          type: string
          description: Phone number of client making order.
          example: "123456789"
        client_email:
          type: string
          description: Email of client making order.
          example: "john@doe.com"
        price:
          type: string
          description: Order's price.
          example: "12.34"
        calories:
          type: number
          description: Calories of dinner in order.
          example: "1234"
        weight:
          type: number
          description: Weight of dinner in order.
          example: "123"
        ingredients:
          type: array
          description: List of ingredient ids in order.
          example: ["610d16", "a63a0"]
    Order:
      allOf:
        - type: object
          properties:
            _id:
              type: integer
              description: The order ID.
              example: 0
            title:
              type: string
              description: Order's name.
              example: "Hot-Dog"
            dinner_id:
              type: string
              description: Dinner's id.
              example: "611273f32335860890b58056"
            client_name:
              type: string
              description: Name of client making order.
              example: "John Doe"
            client_phone:
              type: string
              description: Phone number of client making order.
              example: "123456789"
            client_email:
              type: string
              description: Email of client making order.
              example: "john@doe.com"
            price:
              type: string
              description: Order's price.
              example: "12.34"
            calories:
              type: number
              description: Calories of dinner in order.
              example: "1234"
            weight:
              type: number
              description: Weight of dinner in order.
              example: "123"
            ingredients:
              type: array
              description: List of ingredient ids in order.
              example: ["610d16", "a63a0"]
        - $ref: '#/components/schemas/Order'
tags: [
    {
      name: Order,
      description: API for orders in the system.
    }
  ]
paths:
  /orders:
    get:
      summary: Retrieve a list of Dinners.
      tags:
        - Order
      description: Retrieve a list of dinners from Dinners API.
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
  
  /orders/details/{orderId}:
    get:
      summary: Retrieve details of selected Dinner.
      tags:
        - Order
      description: Retrieve details of selected dinner from Dinners API.
      parameters:
        - name: orderId
          required: true
          in: path
          schema:
            type: string
            description: Dinner id
            example: "6113f20c348351e616b170c4"
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'