const DEFAULT_PORT = 2000;
const OMITTED_INGREDIENTS_KEYS = ["__v", "_id"];
const OMITTED_ORDER_INGREDIENTS_KEYS = ["__v", "selected"];

module.exports = {
  DEFAULT_PORT,
  OMITTED_INGREDIENTS_KEYS,
  OMITTED_ORDER_INGREDIENTS_KEYS,
};
